// @generated by c2b-fixture/generate.mjs; do not edit.
pub const BINDING_IDENTITY: &str = "capsule.governed-deno-core.c2b-fixed-fixture/c1-c2a-v1";
pub const C1_FIXTURE_SHA256: &str = "d5d75e638a15be6c9f4a3230d17309d085f6ec103a73b64d9e0fd656a5423c9e";
pub const C2A_FIXTURE_SHA256: &str = "d4ce88888186266f5d251e6246c889b1fd46d7746bb0ba56bcc4b3ce4675992f";
pub const SOURCE_MEDIA_TYPE: &str = "application/capsule.javascript-source;v=0;module=esm";
pub const INPUT_MEDIA_TYPE: &str = "application/json";
pub const COMPLETION_MEDIA_TYPE: &str = "application/json";
pub const SOURCE_BYTES: &[u8] = include_bytes!("fixtures/main.mjs");
pub const SOURCE_LENGTH: usize = 103;
pub const SOURCE_SHA256: &str = "c8e940feb89b342de2d5e6bd13c413226676de9a539fce34c4107516e635b475";
pub const INPUT_BYTES: &[u8] = include_bytes!("fixtures/input.json");
pub const INPUT_LENGTH: usize = 36;
pub const INPUT_SHA256: &str = "9de0c909cfb111bd99c3b0b5f7a10972894270c2867022a71b6b6f3c0cd1af6e";
pub const COMPLETION_BYTES: &[u8] = include_bytes!("fixtures/completion.json");
pub const COMPLETION_LENGTH: usize = 35;
pub const COMPLETION_SHA256: &str = "bb7234ee486b0fbccc2091859ec93499e6a14ea7d6e091cdef60a0e2a6e8371c";
pub const PAYLOAD_MAXIMUM_BYTES: usize = 262144;
