// Copyright 2018-2026 the Deno authors. MIT license.
// Generates the fixture-specific C2B binding from exact retained C1/C2A bytes.

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const [c1Path, c2aPath, mode = "write"] = process.argv.slice(2);
if (!c1Path || !c2aPath || !["write", "check"].includes(mode)) {
  console.error("usage: generate.mjs C1_FIXTURE C2A_FIXTURE [write|check]");
  process.exit(2);
}

const expected = {
  c1: {
    bytes: 9289,
    sha256: "d5d75e638a15be6c9f4a3230d17309d085f6ec103a73b64d9e0fd656a5423c9e",
  },
  c2a: {
    bytes: 26850,
    sha256: "d4ce88888186266f5d251e6246c889b1fd46d7746bb0ba56bcc4b3ce4675992f",
  },
};

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function fail(message) {
  throw new Error(message);
}

function exactFixture(path, identity, label) {
  const bytes = readFileSync(path);
  if (bytes.length !== identity.bytes || sha256(bytes) !== identity.sha256) {
    fail(`${label} exact-byte identity mismatch`);
  }
  return { bytes, value: JSON.parse(bytes) };
}

const c1 = exactFixture(c1Path, expected.c1, "C1");
const c2a = exactFixture(c2aPath, expected.c2a, "C2A");
if (
  c2a.value.c1Binding?.sha256 !== expected.c1.sha256 ||
  c2a.value.c1Binding?.fixture !==
    "schemas/conformance/c1-governed-deno-core/controlled-development-profile.json"
) {
  fail("C2A does not bind the exact retained C1 fixture");
}

const source = Buffer.from(c2a.value.knownAnswer.source.utf8, "utf8");
const input = Buffer.from(c2a.value.knownAnswer.canonicalInput.utf8, "utf8");
const completion = Buffer.from(
  c2a.value.knownAnswer.expectedCompletion.jsonUtf8,
  "utf8",
);
const sourceMediaType = c1.value.application.source.mediaType;
const inputMediaType = c1.value.application.input.mediaType;
const completionMediaType = c1.value.application.completion.mediaType;

for (
  const [label, bytes, retained] of [
    ["source", source, c2a.value.knownAnswer.source],
    ["input", input, c2a.value.knownAnswer.canonicalInput],
    ["completion", completion, c2a.value.knownAnswer.expectedCompletion],
  ]
) {
  const expectedBytes = retained.bytes ?? retained.jsonBytes;
  const expectedSha256 = retained.sha256 ?? retained.jsonSha256;
  if (bytes.length !== expectedBytes || sha256(bytes) !== expectedSha256) {
    fail(`C2A ${label} retained identity mismatch`);
  }
}
if (
  sourceMediaType !== "application/capsule.javascript-source;v=0;module=esm" ||
  inputMediaType !== "application/json" ||
  completionMediaType !== "application/json"
) {
  fail("C1 media binding mismatch");
}

const binding = {
  objectType: "capsule.governed-deno-core.c2b-fixed-fixture-binding",
  schemaVersion: 1,
  identity: "capsule.governed-deno-core.c2b-fixed-fixture/c1-c2a-v1",
  status: "development-candidate-only-not-execution-or-admission",
  predecessors: {
    c1: {
      bytes: expected.c1.bytes,
      sha256: expected.c1.sha256,
    },
    c2a: {
      bytes: expected.c2a.bytes,
      sha256: expected.c2a.sha256,
    },
  },
  source: {
    path: c2a.value.knownAnswer.source.path,
    mediaType: sourceMediaType,
    bytes: source.length,
    sha256: sha256(source),
    maximumBytes: c1.value.application.source.maximumBytes,
  },
  input: {
    mediaType: inputMediaType,
    encoding: c1.value.application.input.encoding,
    bytes: input.length,
    sha256: sha256(input),
    maximumBytes: c1.value.application.input.maximumBytes,
  },
  completion: {
    mediaType: completionMediaType,
    bytes: completion.length,
    sha256: sha256(completion),
    maximumBytes: c1.value.application.completion.maximumJsonBytes,
    commit: c2a.value.knownAnswer.expectedCompletion.commit,
  },
  runtimeSurface: {
    builtinOps: [
      "op_get_ext_import_meta_proto",
      "op_get_extras_binding_object",
      "op_set_captured_bootstrap",
    ],
    extensions: [],
    moduleLoader: "none",
    inspector: false,
    v8Flags: ["--jitless", "--random-seed=42"],
    inheritedDescriptors: [0, 1, 2],
    workloadBytes: "embedded-exact-retained-c2a-fixture",
  },
  authority: {
    fixedFixtureOnly: true,
    arbitrarySource: false,
    callerPaths: false,
    callerArguments: false,
    callerEnvironment: false,
    runtimeSelection: false,
    runtimeAdmission: false,
    c2bGuestAuthorized: false,
  },
};
const bindingBytes = Buffer.from(`${JSON.stringify(binding, null, 2)}\n`);
const generatedRust = Buffer.from(
  `// @generated by c2b-fixture/generate.mjs; do not edit.
pub const BINDING_IDENTITY: &str = ${JSON.stringify(binding.identity)};
pub const C1_FIXTURE_SHA256: &str = ${JSON.stringify(expected.c1.sha256)};
pub const C2A_FIXTURE_SHA256: &str = ${JSON.stringify(expected.c2a.sha256)};
pub const SOURCE_MEDIA_TYPE: &str = ${JSON.stringify(sourceMediaType)};
pub const INPUT_MEDIA_TYPE: &str = ${JSON.stringify(inputMediaType)};
pub const COMPLETION_MEDIA_TYPE: &str = ${JSON.stringify(completionMediaType)};
pub const SOURCE_BYTES: &[u8] = include_bytes!("fixtures/main.mjs");
pub const SOURCE_LENGTH: usize = ${source.length};
pub const SOURCE_SHA256: &str = ${JSON.stringify(sha256(source))};
pub const INPUT_BYTES: &[u8] = include_bytes!("fixtures/input.json");
pub const INPUT_LENGTH: usize = ${input.length};
pub const INPUT_SHA256: &str = ${JSON.stringify(sha256(input))};
pub const COMPLETION_BYTES: &[u8] = include_bytes!("fixtures/completion.json");
pub const COMPLETION_LENGTH: usize = ${completion.length};
pub const COMPLETION_SHA256: &str = ${JSON.stringify(sha256(completion))};
pub const PAYLOAD_MAXIMUM_BYTES: usize = ${c1.value.application.source.maximumBytes};
`,
);

const outputs = new Map([
  [join(root, "binding.json"), bindingBytes],
  [join(root, "binding.rs"), generatedRust],
  [join(root, "fixtures", "main.mjs"), source],
  [join(root, "fixtures", "input.json"), input],
  [join(root, "fixtures", "completion.json"), completion],
]);

for (const [path, bytes] of outputs) {
  if (mode === "check") {
    const retained = readFileSync(path);
    if (!retained.equals(bytes)) {
      fail(`${path} is not the exact generated output`);
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, bytes);
  }
}

console.log(`binding.identity=${binding.identity}`);
console.log(`binding.sha256=${sha256(bindingBytes)}`);
console.log(`source.sha256=${binding.source.sha256}`);
console.log(`input.sha256=${binding.input.sha256}`);
console.log(`completion.sha256=${binding.completion.sha256}`);
console.log(`mode=${mode}`);
